### ISSUE TITLE
Add mentions to `ref` and the `!` operators.

### ISSUE THREAD

**Issue by agostini01** [mitchell-lang/docs#5]
These could receive a little more attention in any of the tutorials. Maybe on our version of learnxiny

Add mentions to `ref` and the `!` operator.

**Comment by tgiannak** [comment]
I want to wait until we see how people were using it before adding documentation about it.

@sureshjagannathan Do you think we should explain `ref` or just discourage people from using it?

**Comment by sureshjagannathan** [comment]
On Thu, May 16, 2019 at 8:55 PM Theophilos Giannakopoulos <
notifications@github.com> wrote:

> I want to wait until we see how people were using it before adding
> documentation about it.
>
> @sureshjagannathan <https://github.com/sureshjagannathan> Do you think we
> should explain ref or just discourage people from using it?
>

The tutorials discuss "ref", but I think there should probably be something
in the faq that discourages its use.  I also think if there's a tutorial
explaining comprehensions and folds that compares against imperative
techniques.

- Suresh
