### ISSUE TITLE
This is a really interesting declaration.

### ISSUE THREAD

**Issue by agostini01** [mitchell-lang/docs#6]
This is a really interesting declaration.

```
structure C = CartReal(structure DT = DecisionTreeReal);
structure D = C.DT;
```

Does it mean that inside the CartReal sml file, during compilation, I am adding `structure DT = DecisionTreeReal`, so I can use `C.DT`
Or cart real takes an argument, of type `structure` that gets assigned to `DT`.

**Comment by tgiannak** [comment]
This is addressed in the modules section of the external tutorial linked from the tutorials page.
