### ISSUE TITLE
Can we think `let` statements as a way to setup a local "environment" for the function.

### ISSUE THREAD

**Issue by agostini01** [mitchell-lang/docs#7]
Can we think `let` statements as a way to setup a local "environment" for the function.

Anything declared inside a `let`, is only accessible to the subsequent statements of inside the `let` and for any `statement` inside the in.

Also, can we say that what gets evaluate inside the `in` is the returned value of the function `fun forward`.

**Comment by tgiannak** [comment]
What is missing from the description of `let` expressions [here](https://github.com/mitchell-lang/docs/blob/0b0426835f550c36f62a228edfc5d2804d2ecf9b/tutorials/tutorial-gbdt.md#forward)? Do we just need it to be more explicit?

**Comment by tgiannak** [comment]
The addition to the documentation linked above plus the new link to the external tutorial should cover this.
